Yacht-sh/Yacht

app/apps/forms.py, app/apps/views.py, app/templates/apps/deploy_app.html
Updated port field. There's also now a way to add fields. If you remove them all you won't be able to add any though.
=> Deployform

backend/api/db/crud/templates.py, backend/requirements.txt, frontend/package-lock.json
Added the ability to use yaml templates in addition to the json ones.
=> yaml templates are working now

.github/workflows/build-devel.yml, .github/workflows/build-vue.yml, .github/workflows/build.yml, README.md
Sync Develop and build multiarch images.
=> Sync Develop

Dockerfile, nginx.conf, root/etc/services.d/nginx/run
Moved the config for nginx to /etc/nginx/nginx.conf and modified the runfile for nginx to point there.
=> Fix nginx config not copying correctly on NAS OSs

.dockerignore, .gitignore, Dockerfile, backend/.gitignore, backend/alembic.ini, backend/alembic/README, backend/alembic/env.py, backend/alembic/script.py.mako, backend/api/actions/apps.py, backend/api/db/crud/templates.py, backend/api/db/models/__init__.py, backend/api/db/models/containers.py, backend/api/db/schemas/apps.py, backend/api/db/schemas/templates.py, backend/api/main.py, backend/api/utils.py, backend/requirements.txt, frontend/src/components/applications/ApplicationDetailsComponents/AppContent.vue, frontend/src/components/applications/ApplicationsForm.vue, frontend/src/store/modules/apps.js, root/etc/cont-init.d/30-config, root/etc/cont-init.d/31-migrate
Added Devices and Labels to templates; added automatic db migrations; fixed pulling all images when not specifying a tag by auto appending latest if none is set; misc fixes
=> Port labels

backend/api/actions/apps.py, frontend/src/components/serverSettings/Prune.vue, frontend/src/components/serverSettings/ServerUpdate.vue
Added error handling to updating apps and yacht's self updating feature.
=> Error Handling

backend/api/actions/apps.py, backend/api/actions/resources.py, backend/api/main.py, backend/api/routers/app_settings.py, backend/api/routers/resources.py, backend/api/settings.py, frontend/src/components/applications/ApplicationsList.vue, frontend/src/components/images/ImageDetails.vue, frontend/src/components/images/ImageList.vue, frontend/src/components/nav/Sidebar.vue, frontend/src/router/index.js, frontend/src/store/index.js, frontend/src/store/modules/images.js, frontend/src/views/Home.vue, frontend/src/views/Images.vue
Implemented basics of image management.
=> Image Managment

backend/api/auth/auth.py, backend/api/main.py, backend/api/routers/app_settings.py, backend/api/routers/auth.py, backend/api/routers/user.py, backend/api/utils.py, frontend/src/App.vue, frontend/src/components/auth/LoginForm.vue, frontend/src/components/nav/Appbar.vue, frontend/src/store/actions/auth.js, frontend/src/store/modules/auth.js
Disable auth by setting `DISABLE_AUTH=True`
=> Disable Auth Variable

backend/api/actions/resources.py, backend/api/db/schemas/resources.py, backend/api/routers/resources.py, frontend/src/components/resources/networks/NetworkForm.vue, frontend/src/components/resources/networks/NetworkList.vue, frontend/src/router/index.js
Added network creation form. Looking for feedback if anyone has any.
=> Added network creation form

README.md
Signed-off-by: Akashdeep Dhar <akashdeep.dhar@gmail.com>
Fixes https://github.com/SelfhostedPro/Yacht/issues/308.
=> Fixed execution command for Docker container

backend/api/routers/users.py
Here is the fix for case sensitive user names, it should handle oddball cases like special characters just fine
fixes [#328]
=> use casefold() for username matching

backend/api/db/crud/users.py
My previous PR left errors with setting usernames that I missed, but now it
works as intended.  I did not get the user password don't change on an
empty string because I think it would require a change in how the user
is handled in the backend.  I also cleaned up a print function here that
was printing an ugly object reference on a name change, so now it shows old/new
usernames if they are changing.
=> actually fixes [SelfHostedPro#328]

frontend/src/atoms.ts, frontend/src/components/AppsTable.tsx
This adds in the table with hostPort and hostId
=> this works to get hostIp and hostPort into the table

scripts/dev.sh, scripts/functions.sh
lots of cleanup, a little more documentation, and some testing with
using tmux so you can see the status of each running process
(frontend/backend) at the same time
=> update dev scripts, add more documentation/cleanup

frontend/src/views/Home.vue
Should fix dashboard making multiple calls for each app, which may be causing other errors. Basically, there are 2 loops which went through each app  and created a new connection to the stats but it works without it. The rest of the edits were from prettier doing its thing.
=> remove loop making multiple calls to stats when one will do

docker-compose.yml
Adding docker-compose example to the base directory. 
Addition to [[Feature Request] Docker-Compose for Dev use #459](https://github.com/SelfhostedPro/Yacht/issues/459)
=> Adding docker-compose example to base directory

docker-compose.yml
Updated docker-compose to match install instructions on the yacht install page. https://yacht.sh/docs/Installation/Install/
=> Updated docker-compose

README.md
Updated readme.md instructions for installing Docker and Yacht inside of WSL2 on Windows.
=> Updates readme for wsl2 support notes

Dockerfile
Error with  echo "**** Cleaning Up ****" &&\
apk del --purge \
build-dependencies && \
rm -rf \
/root/.cache \
/tmp/*
Replaced with
RUN apk del --purge build-dependencies && \
rm -rf /root/.cache /tmp/*
=> Updating docker file

.idea/.gitignore, .idea/.idea.Yacht.dir/.idea/encodings.xml, .idea/.idea.Yacht.dir/.idea/indexLayout.xml, .idea/.idea.Yacht.dir/.idea/projectSettingsUpdater.xml, .idea/.idea.Yacht.dir/.idea/vcs.xml, .idea/.idea.Yacht.dir/.idea/workspace.xml
Reverts SelfhostedPro/Yacht#696
=> Revert "Wicked testdeploy"
